[package]
name = "bardance"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
lazy-regex = "3.4"
symphonia = { version = "0.5", default-features = false, features = ["wav", "pcm", "isomp4", "aac", "alac", "mp3"] }
